**1 - Dimenstion**

In [1]:
import numpy as np
f = np.array([10,14,24,35,60])
print(f)
print(f.ndim)
print(f.shape)

[10 14 24 35 60]
1
(5,)


In [2]:
print(f[2])

24


##1. Create 1 to 10 numbers data in 1-dimenstions on x - axis





In [3]:
t = []
for i in range(11):
  t.append(i)
  y = np.array(t)
print(y)
print(y.ndim)
print(y.shape)

[ 0  1  2  3  4  5  6  7  8  9 10]
1
(11,)


**2 - Dimenstion**

In [4]:
f = np.array([[10,1,9],[3,6,7],[2,4,8]])
print(f)
print(f.ndim)
print(f.shape)
print(f.size)

[[10  1  9]
 [ 3  6  7]
 [ 2  4  8]]
2
(3, 3)
9


In [5]:
print(f[1][2])

7


In [6]:
print(f[2][1])

4


##2. Create 1 to 10 numbers data in 2-dimenstions on x - axis

In [7]:
import numpy as np
t = []
for i in range(10):
  t.append(i)
  y = np.array(t)
print(y)
print(y.ndim)
print(y.shape)
b = y.reshape(2,5)
print(b)



[0 1 2 3 4 5 6 7 8 9]
1
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]


**Converting 1D to 2D**

In [8]:
a = np.array ([10,11,14,17,19,16])
print(a)
print(a.ndim)
print(a.shape)
b = a.reshape(2,3)
print(b)
print(b.ndim)
print(b.shape)

[10 11 14 17 19 16]
1
(6,)
[[10 11 14]
 [17 19 16]]
2
(2, 3)


##If I want to access 1 to 60 then we can't write in a line so we will use arange

In [9]:
a = np.arange(1,61)
print(a)
print(a.ndim)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
(60,)


Changing 1-D to 2-D data

In [10]:
a = np.arange(1,61)
print(a)
print(a.ndim)
print(a.shape)
b = a.reshape(10,6)
print(b)
print(b.ndim)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
(60,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2
(10, 6)


In [11]:
a = np.arange(1,61).reshape(10,6)
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2
(10, 6)


In [12]:
print(a[2][1])

14


In [13]:
print(a[7][3])

46


Changing 1-D to 3-D data

In [14]:
a = np.arange(1,61).reshape(5,2,6)
print(a)
print(a.ndim)
print(a.shape)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
(5, 2, 6)


In [15]:
print(a[0][1][1])

8


In [16]:
print(a[0][0][1])

2


In [17]:
print(a[4][1][3])

58


In [19]:
print(a[3][0][0])

37


In [20]:
print(a[3][1][4])

47


##reshape (-1,1) and reshape (1,-1)

In [21]:
import numpy as np

a = np.array([10,11,14,7,9])
print(a)
print(a.ndim)
print(a.shape)
b = a.reshape(1,-1)
print(b)
print(b.ndim)
print(b.shape)


[10 11 14  7  9]
1
(5,)
[[10 11 14  7  9]]
2
(1, 5)


In [22]:
a = np.array([10,11,14,7,9])
print(a)
print(a.ndim)
print(a.shape)
b = a.reshape(-1,1)
print(b)
print(b.ndim)
print(b.shape)

[10 11 14  7  9]
1
(5,)
[[10]
 [11]
 [14]
 [ 7]
 [ 9]]
2
(5, 1)


##2D to 3D

In [23]:
a = np.array([[10,1,9],[3,6,7],[2,4,8]])
print(a)
print(a.ndim)
print(a.shape)
b = a.reshape(1,3,3)
print(b)
print(b.ndim)
print(b.shape)

[[10  1  9]
 [ 3  6  7]
 [ 2  4  8]]
2
(3, 3)
[[[10  1  9]
  [ 3  6  7]
  [ 2  4  8]]]
3
(1, 3, 3)


##zeros function

In [24]:
a = np.zeros((5,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
a = np.zeros((5,4) , dtype = np.int32)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##ones function

In [26]:
a = np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
a = np.ones((5,4),dtype = np.int32)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##Full function

In [28]:
a = np.full((5,4),7)
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [29]:
a = np.full((5,4),6)
print(a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


##eye function

In [ ]:
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [30]:
a = np.eye(9)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


##diag function

In [31]:
a = np.diag([10,20,30,40])
print(a)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


##Numpy--->random--->randint

In [32]:
a = np.random.randint(10,50)
print(a)

41


In [33]:
a = np.random.randint(10,50,3)
print(a)

[35 12 16]


##Numpy--->random--->rand(0 to 1)

In [34]:
a = np.random.rand(5,6)
print(a)

[[0.77395283 0.4006809  0.98719536 0.88991199 0.92623674 0.73652892]
 [0.06045945 0.82555387 0.31318205 0.50432862 0.40319959 0.36570076]
 [0.4944633  0.59090145 0.98893309 0.54709021 0.80679285 0.04527245]
 [0.37217052 0.956523   0.75024829 0.99999506 0.1868015  0.72820663]
 [0.20509704 0.87996144 0.87340285 0.53452441 0.29249937 0.41197322]]


##Numpy--->random--->random(0 to 1)

In [35]:
a = np.random.random((5,6))
print(a)

[[0.35783109 0.33123824 0.67960627 0.63788934 0.03764998 0.84430835]
 [0.2714606  0.66496204 0.55256152 0.76279133 0.73045002 0.55399718]
 [0.77430534 0.2378685  0.58016484 0.76559675 0.23347202 0.01704187]
 [0.49263356 0.24105753 0.82863204 0.38096319 0.23486657 0.26627137]
 [0.23287797 0.50339812 0.43676508 0.02254637 0.83019775 0.74765138]]


##Numpy--->random--->randn(-1 to 1)

In [36]:
a = np.random.randn(5,4)
print(a)

[[-1.39652025 -0.08404898  0.15988961  0.36641091]
 [ 2.65901969 -1.84809963  0.68620947 -0.27992843]
 [-0.24823395  1.47133326  0.68077227  1.33334675]
 [ 0.9324397   0.97342497 -1.7911646  -0.88188519]
 [-0.48957514  0.12609    -0.60522162 -0.38453013]]


##ravel--->Any type of data to 1D data

In [37]:
a = np.array([[10,1,9],[3,6,7],[2,4,8]])
print(a)
print(a.ndim)
print(a.shape)
b = np.ravel(a)
print(b)
print(b.ndim)
print(b.shape)

[[10  1  9]
 [ 3  6  7]
 [ 2  4  8]]
2
(3, 3)
[10  1  9  3  6  7  2  4  8]
1
(9,)


##Transpose

In [38]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
print(np.transpose(a))

[[10  2  8]
 [20  5 19]
 [ 4  6  2]]


##concatination

In [39]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
b = np.array([[11,3,19],[1,7,23],[5,9,17]])
c = np.concat((a,b))
print(c)

[[10 20  4]
 [ 2  5  6]
 [ 8 19  2]
 [11  3 19]
 [ 1  7 23]
 [ 5  9 17]]


**axis = 1 axis = 0 **

##sum

In [40]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
print(np.sum(b))

95


In [ ]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
print(np.sum(b, axis=0))

[17 19 59]


##Max

In [41]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
print(np.max(b))

23


In [ ]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
print(np.max(b, axis=0))

[11  9 23]


In [ ]:
a = np.array([[10,20,4],[2,5,6],[8,19,2]])
print(np.max(b, axis=1))

[19 23 17]


In [ ]:
import numpy as np

a = np.array([10,20,4])
print(type(a))

<class 'numpy.ndarray'>


For example, let's compare two arrays values to get the maximum of each.

In [42]:
# random array
x = np.random.randn(8)
x

array([-0.1051238 ,  1.17424317, -0.87212666, -0.43943958, -1.08251749,
       -0.05679682, -0.03980404,  1.74152882])

In [43]:
# another random array
y = np.random.randn(8)
y

array([ 1.4956824 ,  0.71326508, -0.01359582, -1.52218313, -1.02557565,
       -0.63285068, -0.70988943,  0.31167195])

In [44]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 1.4956824 ,  1.17424317, -0.01359582, -0.43943958, -1.02557565,
       -0.05679682, -0.03980404,  1.74152882])

##Min

In [47]:
b = np.array([[10,3,2],
               [1,6,4],
               [9,7,8]])
print(np.min(b))

1


In [48]:
b = np.array([[10,3,2],
               [1,6,4],
               [9,7,8]])
print(np.min(b,axis=1))

[2 1 7]


In [49]:
b = np.array([[10,3,2],
               [1,6,4],
               [9,7,8]])
print(np.min(b,axis=0))

[1 3 2]


##argmax

In [53]:
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.argmax(b))

0


In [54]:
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.argmax(b,axis=1))

[0 1 0]


In [56]:
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.argmax(b,axis=0))

[0 2 2]


##argmin

In [57]:
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.argmin(b))

3


In [59]:
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.argmin(b,axis=1))

[2 0 1]


In [60]:
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.argmin(b,axis=0))

[1 0 0]


##repeat

In [61]:
a = np.arange(10,21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [63]:
a = np.arange(10,21)
b = a.reshape(1,-1)
print(b)

[[10 11 12 13 14 15 16 17 18 19 20]]


In [69]:
a = np.arange(10,16)
b = a.reshape(1,-1)
c = np.repeat(b,5,axis=0)
print(c)

[[10 11 12 13 14 15]
 [10 11 12 13 14 15]
 [10 11 12 13 14 15]
 [10 11 12 13 14 15]
 [10 11 12 13 14 15]]


In [71]:
a = np.arange(10,16)
b = a.reshape(1,-1)
c = np.repeat(b,5,axis=1)
print(c)

[[10 10 10 10 10 11 11 11 11 11 12 12 12 12 12 13 13 13 13 13 14 14 14 14
  14 15 15 15 15 15]]


Some math operations

In [74]:
a = np.array([[10,1,9],[3,6,7],[2,4,8]])
b = np.array([[10,3,2],[1,6,4],[9,7,8]])
print(np.add(a,b))

[[20  4 11]
 [ 4 12 11]
 [11 11 16]]


In [75]:
print(np.subtract(a,b))

[[ 0 -2  7]
 [ 2  0  3]
 [-7 -3  0]]


In [76]:
print(np.multiply(a,b))

[[100   3  18]
 [  3  36  28]
 [ 18  28  64]]


##matmul

In [77]:
a = np.array([[1,4],[7,6]])
b = np.array([[4,3,2],[1,8,6]])
print(np.matmul(a,b))

[[ 8 35 26]
 [34 69 50]]


for loop in numpy

In [78]:
a = np.array([[10,1,9],[3,6,7],[2,4,8]])
for i in a:
  print(i)
  print('GM')

[10  1  9]
GM
[3 6 7]
GM
[2 4 8]
GM


In [81]:
a = np.array([[10,1,9],[3,6,7],[2,4,8]])
for i in a:
  for j in i:
    if j%2!=0:
      print(j)

1
9
3
7
